Version 4
SymbolType BLOCK
LINE Normal -32 48 -32 -48
LINE Normal 64 0 -32 48
LINE Normal -32 -48 64 0
LINE Normal -32 0 -48 0
LINE Normal 16 24 16 48
LINE Normal 64 0 80 0
WINDOW 0 -32 -48 Bottom 2
WINDOW 3 -32 64 Top 2
SYMATTR Prefix X
SYMATTR Value BGA614
SYMATTR ModelFile C:\Users\giorg\AppData\Local\LTspice\lib\sym\AutoGenerated\BGA614.net
PIN -48 0 BOTTOM 8
PINATTR PinName 1
PINATTR SpiceOrder 1
PIN 16 48 RIGHT 8
PINATTR PinName 2
PINATTR SpiceOrder 2
PIN 80 0 BOTTOM 8
PINATTR PinName 3
PINATTR SpiceOrder 3
